Add TIAGo pro demo
agimus-project/agimus-demos pull request #20
Opened 2024-12-19 09:26 UTC by thomaspeyrucain

2025-03-05 07:51 UTC, jmirabel reviewed
One minor comment: in agimus_demos_common, instead of prefixing the filenames by `robotmodel_`, can you create a directory for that robot pls?
If you don't want to touch franka files, you can create the tiago ones in a directory.

This is not testable without a docker with alum, right?

2025-03-05 08:11 UTC, MaximilienNaveau commented on agimus_demo_02_simple_pd_plus_tiago_pro/launch/bringup.launch.py
> +            return [pd_plus_controller_node]  # Activate custom control
Not sure. I could try to see what's inside.

2025-03-05 08:22 UTC, MaximilienNaveau commented on agimus_demo_02_simple_pd_plus_tiago_pro/tests/test_integration.py
I will remove them

2025-03-05 08:23 UTC, MaximilienNaveau commented on agimus_demos_common/package.xml
Nope thanks for noticing!

2025-03-05 10:08 UTC, jmirabel commented
> > One minor comment: in agimus_demos_common, instead of prefixing the filenames by `robotmodel_`, can you create a directory for that robot pls? If you don't want to touch franka files, you can create the tiago ones in a directory.
> 
> I am not sure I follow. You would imagine a different package agimus_demos_common_tiago or something? Or is it something else?

No I have in mind something like config/tiago/foo.yaml instead of config/tiago_foo.yaml

And the same for some other files. This is a minor remarks.

2025-03-05 10:12 UTC, MaximilienNaveau commented
> > > One minor comment: in agimus_demos_common, instead of prefixing the filenames by `robotmodel_`, can you create a directory for that robot pls? If you don't want to touch franka files, you can create the tiago ones in a directory.
> > 
> > 
> > I am not sure I follow. You would imagine a different package agimus_demos_common_tiago or something? Or is it something else?
> 
> No I have in mind something like config/tiago/foo.yaml instead of config/tiago_foo.yaml
> 
> And the same for some other files. This is a minor remarks.

Ok I understand better. we can do this for the config. I am unsure about the launch files though.

2025-03-05 10:18 UTC, jmirabel commented
I don't think it would be weird the way I see it.
Nevermind, keep it this way it is now.

2025-03-05 11:22 UTC, MaximilienNaveau commented on agimus_demo_02_simple_pd_plus_tiago_pro/launch/bringup.launch.py
> +            return [pd_plus_controller_node]  # Activate custom control
I add a check on the return code

2025-03-05 12:30 UTC, jmirabel commented on agimus_demos_common/package.xml
I'm skeptical about the dependencies. In my current setup, there is no Tiago packages. Will I be able to install the agimus demos ?

2025-03-05 14:19 UTC, MaximilienNaveau commented on agimus_demos_common/package.xml
I could remove them. But then we would better have the franka_demos_common and the tiago_pro_demos_common pacakges?

2025-03-05 14:20 UTC, MaximilienNaveau commented
> I don't think it would be weird the way I see it. Nevermind, keep it this way it is now.

I refactored to take into account your comments.

2025-03-10 10:52 UTC, MaximilienNaveau commented
@Kotochleb @TheoMF can you have a quick look an tell me if that make sens to you?

2025-03-14 10:30 UTC, Kotochleb requested changes

2025-03-14 10:30 UTC, Kotochleb commented on agimus_demos_common/agimus_demos_common/launch_utils.py
There is a mismatch where some of the boolean parameters are `True/False` and some are `true/false`. IMO those should be unified. The question is which to choose... At first I went with full lower case as I was used to this notation from ROS 1, but I see you chose capsized first letters as I guess this is a practice at PAL. The one you chose makes more sense in cases with `PythonExpression`, where the string is evaluated to python expression. @MaximilienNaveau  @thomaspeyrucain  what do you guys think? If needed, we can switch all to capitalized first letter. Just that it will "break" the compatibility, but with 5 users I guess we can afford that

2025-03-14 10:30 UTC, Kotochleb commented on agimus_demos_common/agimus_demos_common/launch_utils.py
> +            choices=["omni_base"],
This is a naming for ROS frame id or what? Other parameters are separated with `-` while this one uses `_`. If there a reason for that?

2025-03-14 10:30 UTC, Kotochleb commented on agimus_demos_common/package.xml
I don't think we can treat dependencies from package.xml as option. Whole package can be optional, but when you install it you want to make sure there is no missing dependency in a default setup. Adding Tiago by default will definitely make build of the docker break and this will be annoying for all the users. We can do this.
```xml
 <!-- Franka dependencies. -->
  <exec_depend condition="$AGIMUS_DEMOS_BUILD == franka">franka_description</exec_depend>
  <exec_depend condition="$AGIMUS_DEMOS_BUILD == franka">franka_gripper</exec_depend>


  <!-- Tiago-Pro dependencies. -->
  <exec_depend condition="$AGIMUS_DEMOS_BUILD == tiago">tiago_description</exec_depend>
  <exec_depend condition="$AGIMUS_DEMOS_BUILD == tiago">tiago_pro_gazebo</exec_depend>
```

Then when we will be building the package we need to create an environment variable `AGIMUS_DEMOS_BUILD` that will set the packages accordingly. Rosdep will respect that flag, same goes for colcon.

2025-03-14 16:39 UTC, TheoMF commented on agimus_demos_common/agimus_demos_common/launch_utils.py
> +        ),
these two parameters are already in the launch_utils of the humble-devel branch

2025-03-17 11:33 UTC, MaximilienNaveau commented on agimus_demo_02_simple_pd_plus_tiago_pro/launch/bringup.launch.py
what do you mean? you mean one pacakge for the demo but 2 bringup launch files?

2025-03-21 16:47 UTC, MaximilienNaveau commented on agimus_demo_02_simple_pd_plus_tiago_pro/README.md
I have an issue with how we present the demo in the README as we do not present the docker and what's inside.

We say clone everything including all HPP, croccodyl etc. without notifying that the code is pre-built in a docker?

2025-04-18 08:40 UTC, MaximilienNaveau approved these changes

2025-04-18 08:40 UTC, MaximilienNaveau commented on agimus_demos_common/agimus_demos_common/launch_utils.py
I don't care much.
Let's leave it like this for now if you don't mind we need to investigate the tiago code base to verify if this capital letter is needed or if it's an artifact of the developer.
I would assume that when you test a string as argument you either test s1.lower == s2.lower()
Or you impose the exact 2 strings False/True as argument.
Not sure how it is for now and we should move forward so... TBD
https://github.com/agimus-project/agimus-demos/issues/103

2025-04-18 08:40 UTC, MaximilienNaveau commented on agimus_demos_common/agimus_demos_common/launch_utils.py
> +        launch_arguments={
no idea haha. For now it works as expected in the downstream launch file.

2025-04-18 08:40 UTC, merged